.TH "AdvanceMAME Bluetooth Daemon" 1
.SH NAME
advblue \- AdvanceMAME Bluetooth Daemon
.SH SYNOPSIS 
advblue [\-f]
.PD 0
.PP
.PD
.SH DESCRIPTION 
The \`advblue\' utility is a daemon that is able to
pair and connect automatically bluetooth joysticks.
.PP
It uses the /usr/bin/bluetoothctl tool to communicate
with the devices.
.PP
To start it, just run it without any argument.
.SH OPTIONS 
These are the command line options supported:
.TP
.B \-f
Run in foreground mode. The interation with the
bluetoothctl program is printed on the terminal.
.SH COPYRIGHT 
This file is Copyright (C) 2018 Andrea Mazzoleni.
