.TH "AdvanceMAME Joystick Tester" 1
.SH NAME
advj \- AdvanceMAME Joystick Tester
.SH SYNOPSIS 
advj [\-device_joystick DEVICE] [\-log] [\-logsync]
.PD 0
.PP
.PD
.SH DESCRIPTION 
The \`advj\' utility calibrates and tests the joystick.
.PP
The calibration data is not saved in the AdvanceMAME
configuration file. You must repeat the calibration process
in the emulator.
.PP
Check the \`advdev.txt\' file for the description of the
\`device_joystick\' option.
.SH COPYRIGHT 
This file is Copyright (C) 2003 Andrea Mazzoleni.
